FROM node:12

ENV EXPO_DEBUG=true

WORKDIR /workspace

COPY app/package.json /workspace/package.json
COPY app/yarn.lock /workspace/yarn.lock
RUN yarn install --production=false

COPY /app .

RUN rm appsettings.json
RUN mv appsettings.prod.json appsettings.json

RUN yarn build-web
