FROM stefanscherer/node-windows:10

ENV EXPO_DEBUG=true

WORKDIR /workspace

COPY app/package.json /workspace/package.json
COPY app/yarn.lock /workspace/yarn.lock
RUN yarn cache clean
RUN yarn install --production=false

COPY /app .

# these are run in the appveyor.yml
# RUN del appsettings.json
# RUN move appsettings.prod.json appsettings.json

RUN yarn build-web
